
# https://gall.dcinside.com/mabi_heroes2/1066556 done
# https://gall.dcinside.com/mabi_heroes2/1022016 done

blocks = [
    'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=58973', # 入口1
    'https://gall.dcinside.com/mabi_heroes2/58973', # 入口2
    'https://gall.dcinside.com/mabi_heroes2/1322243' # 煙花暗殺者重複url
]
# update: 2023-04-24
items = [
{'name': '黑貓乳膠', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1592464'},
{'name': '葉織詩篇', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1584363'},
{'name': '露背毛衣', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1557131'},
{'name': '白色救世主', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1494565'},
{'name': '吊帶牛仔褲', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1422965'},
{'name': '月下祈禱', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1422963'},
{'name': '現代騎士', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/1365981'},
{'name': '性感喵喵', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/1347825'},
{'name': '職業', 'type': 'main','url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=757019'},
{'name': '光輝騎士', 'type': 'main','url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=970634'},
{'name': '紫蝶、赤蝶翩舞', 'type': 'main','url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=628410'},
{'name': '花邊', 'type': 'main','url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=734453'},
{'name': '公路騎士', 'type': 'main','url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=804239'},
{'name': '月光女神', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=512433'},
{'name': '盔甲系列', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=858790'},
{'name': '提爾', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=629408'},
{'name': '神聖光輝', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=612507'},
{'name': '暗黑女王', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=500355'},
{'name': '水晶清透', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=629184'},
{'name': '熱帶風情海灘', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=748652'},
{'name': '都市機能服貓神', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes&no=10761749'},
{'name': '精靈遊俠、貓神', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=629386'},
{'name': '露肩', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=175415'},
{'name': '條紋連身衣', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=281210'},
{'name': '兔女郎', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=63161'},
{'name': '惡魔女僕', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=538554'},
{'name': '女伶', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1173189'},
{'name': '秋夜晚宴', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1318178'},
{'name': '煙花暗殺者', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1322243'},
{'name': '空服員', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1331113'},
{'name': '精靈衛士', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1222467'},
{'name': '勞拉', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1174050'},
{'name': '平衡訓練', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1114572'},
{'name': '科技放克風', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/1114622'},
{'name': '閃亮名媛', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1062328'},
{'name': '經典鑲邊西裝', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1009586'},
{'name': '天仙', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=962041'},
{'name': '反差感睡衣', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=955837'},
{'name': '惡魔熊睡衣', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=958360'},
{'name': '希耶媞', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=906400'},
{'name': '束帶迷你連衣裙', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=844720'},
{'name': '白玉壺', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=774923'},
{'name': '美大生', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=748568'},
{'name': '星光透視', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=688583'},
{'name': '艾波娜', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/435342'},
{'name': '黑色風信子', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=254787'},
{'name': '輕柔旗袍', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=68855'},
{'name': '黃金芭絲特', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=175194'},
{'name': '花魁、和服、浴衣', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=811037'},
{'name': '月季', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/274839'},
{'name': '禁錮之羽', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=628938'},
{'name': '真理褲', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=390836'},
{'name': '慢跑運動服', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/998835'},
{'name': '倩影特務', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=281230'},
{'name': '休閒寬鬆網格', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/628488'},
{'name': '夜金凜、黃金旗袍、東方玫瑰', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=628376'},
{'name': '辦公室女郎', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1062351'},
{'name': '哥德風惡魔、魅惑將校', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=998846'},
{'name': '惡魔突擊者', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1322838'},
{'name': '妮潘', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=274881'},
{'name': '婚紗', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/1118135'},
{'name': '霧櫻、阿爾卡娜', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/629173'},
{'name': '小鬼', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=990088'},
{'name': '韓服', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=628995'},
{'name': '不知火舞', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/629375'},
{'name': '蕾吉娜、伊瑟特、黑尖晶石', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=628482'},
{'name': '稻荷巫女', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=897420'},
{'name': '艦隊水手', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=734031'},
{'name': '紅魔', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=436374'},
{'name': '魅魔', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=465699'},
{'name': '幼兒園、邦妮兔', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=945226'},
{'name': '可愛恐龍', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/628462'},
{'name': '歌德', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1068273'},
{'name': '佛朗明哥', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1091852'},
{'name': '羈絆', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=281330'},
{'name': '內衣', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/397676'},
# {'name': '蕾吉娜', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=879683'},
# {'name': '寵物', 'type': 'main', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=506425'},
# {'name': 'AI繪圖', 'type': 'main', 'url': 'https://gall.dcinside.com/mabi_heroes2/1262750'},
{'name': 'AI繪圖', 'type': 'detail', 'url': 'https://gall.dcinside.com/board/view/?id=mabi_heroes2&no=1259934'},
{'name': '隨機', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/964432'},
{'name': '隨機', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/964440'},
{'name': '隨機', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/964444'},
{'name': '貓女', 'type': 'main', 'url': 'https://gall.dcinside.com/m/sekigyurem/1785'},
{'name': '孔雀', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/629412'},
{'name': '兔女郎', 'type': 'detail', 'url': 'https://gall.dcinside.com/mabi_heroes2/622085'},

]